---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-auth
    namespace: apps
stringData:
    password: ENC[AES256_GCM,data:3ajxBsbajyJfBG9bc96Fo160IEnM2CgNCb8=,iv:srm1yM7D2bJRgJH8Kv+YESug5s30axUWKkeaa2838B8=,tag:KVtNH7Md3oD108Bh3l6W9Q==,type:str]
    username: ENC[AES256_GCM,data:1GYzaHCZ7gpd7t7/pUpCIv8N,iv:jMbpvzRkjAVk//Fx57m17d2jtivMMtcO8D0k8GtQzSY=,tag:OBGBSaKeFwvKYlJw54gvBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-29T10:12:27Z"
    mac: ENC[AES256_GCM,data:kTSF70yRk/g1Uc35XpD84ZZJo33aLWunnw5RRxT0CcIX0ou9uvF67qJi/qu9OZ1s5sbakfdUHDRkMb8MNv604fEnZc5Uow7mkCUbhMaQ+ZbA8GLjO6OTnacBzrLFDr6xfKtFjmH3Z7N1J6MCGSvbY616pQ0HKEXrCJURFo0gSY4=,iv:RgoIksTGKbGU1ImP4ivWxIrt38tf1D+z5cIddepjXLo=,tag:PzQBA8mxyXM8+do3Z9MlkA==,type:str]
    pgp:
        - created_at: "2023-10-29T10:12:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA32HWVix55BFAQ//b+3KlK5u9Bn0rYOROBRyiUaiZPeZLUccpbD+pI1sfER0
            gZYckhU5IgTVi9wA59CTeMwH3069t1HyAYu9U/N/y4pYmNV5Zrh44FNJ4c619Wo/
            1tB4hgh8TwY91YEN+H83WrmUYXlsiamxqyXd+eBhJn3Ld8Gjl7NuPk+2UBO1UUjK
            I7nG44rTOqt0DCYj8jqYsEpGftWGLPuzcIRdeaOTrxxjQAztOCyZQpcJvn7oVjmF
            yruQuuIHKZ2tUNcwpC2WtFFwkTPeieABz0DxlGd+7jaRqbw1DHRgggESw4Z3COv5
            RGRv5A0KXbLylMm5ubz2oDuQtY2uNJMy2HiJArk7cAHwusBHPaGkrhrwatIrjsVf
            vRAsL6cGnFxgLwP2Fbi218QOpiPSaFx/2xdQBOoU6gHo6MeBRpe+oOjxUAgHaOvM
            jHKw335nBkIiknYwiWuYiw2+zp2CeT23tjrAst1vDtElTopAB39JY0wbr4h9tVi0
            C65wARhgq1OY3n0UpB5mZEty3slwYH5tO3K0t3LZNEq4AEa08JnM8jRc79R3peb1
            gCSbXUGxmd9+Xg9Xhvd6idANHQUowDwL3ieU8uBMxyXrWCdM+1XKq3mFqYNQtBIw
            lhNUcQWEYdLnjhPHJbdAdHtpbvjoBVAyyzF9E+1Ecnsqnton5oofEoBlfs0DzWLU
            ZgEJAhDl+NSoLmEyATFPr/Ru08hMmoAWwjnLa42O0wJIVSK/ZxMF7mb41L+5Kh8P
            YaKtdS4HkZSo8CUIYGhrhC2I+vG9CrHh4taXPAP2J5Eljkz9/MpnF8zEyLmbCmez
            jYGZV3d1Ww==
            =s2L2
            -----END PGP MESSAGE-----
          fp: EF2F4F42E1526D2213862B35FFABFC4B0B73F199
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitlab-auth
  url: https://gitlab.com/abohmeed/myweatherapp
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: gitlab-auth
  type: oci
  url: oci://registry.gitlab.com/abohmeed/myweatherapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-hcvault
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
