---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-auth
    namespace: apps
stringData:
    password: ENC[AES256_GCM,data:+PBKp479XlbEho1IZgSixovfSqcoSq46yeg=,iv:abB8MAcXRa7dEUhtYC6QAC+HHLRJfyNZ7PQCcaMctqg=,tag:HGXwDuZIkO1lKPu1bAM4FA==,type:str]
    username: ENC[AES256_GCM,data:2mnDcLxuc/oGgzxo5S2k/t5m,iv:+fp+F/7LdkT25CvFSMSqRkVsKeITZlfFF9bEw7ZNunI=,tag:VB89VPwthZd9eVlbDmJULg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-02T09:15:02Z"
    mac: ENC[AES256_GCM,data:eCSVgAMepg9jymaqFzG3bAJGq/tin4XlH0jTfaNTJJz/YHdfLGldlbuichbtpvmB0+6fLYQj37r7QJ33l74QvBoFi2MPCfAwuNdQ9XizjtOJ6jCvJTlSVyjxVxrgQ26WRIAuH6L2txXzNjdi7D0ZHjk9/ZdVzfDgfGWcw82UD94=,iv:mR3B9niExvMCeONXfphXjALpKB4iKSBme07Ngd3xy2s=,tag:i3SB4ZajV5PGOhFC+Sx6Lw==,type:str]
    pgp:
        - created_at: "2023-09-02T09:15:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx546Ghm4HPxARAAkqieO1aVDCA5n7qEFBW4kNsF2i0LUsmjx5vYGouccmAq
            /MisKF7LhA56iqXU8VvQ5x6ttV6c5+CIUt49lvkYKUEGnYb4MSU+VxfUZ91aMtCB
            R+2vmylkexqI6+eJliWcN0otgJN8JCNiCpe+mqFxCniHH6CMjI+deXfFU0tpbYga
            5soPT6q9FEoSZJYmW2IOxTZxHyl5on7Ro6GTY3tyZE+Wu1i1RDaXrrjoDoCB7mUv
            FYoUIGGIONEF0viIFamkQJhNH8QRIUQjPYuZhoUzUoFe8F7zUfGgLRmkRdfOFhcE
            LYdtt3NPg5hXfXGVodZGBP8Z2ypfp05CbqpbK0BeJlAuZmpsYAD2WqYK5IGIFsBR
            GJOUdH/+Ic9gMt7KZ67WRAH/sE26JchmXEISL2G2fpdKqFZolbv5eD4TIrbghhjs
            2DM4SODejpRgSC+QMyQmIOEnqkRgZJwzXIYIUWd4JUtE53q5EJyd4gqjTmH8VWpR
            gUgsjcd1jQK3F816M1XDRBHNJiGDqCFQeQFKlVokN615wscPuefzxLg9lsuNIcD+
            RYUXPpCyCHa+eew/igg43Lm44gRhYiKeuY8XQKNgfz+z+I8nUGYHUPuUZsZoKPc8
            qMLhN36dHztrTpi9U4F/JH4wD3mWzodZf4875c2yp3fBU+5k4CF/0LPavs/bQZXS
            XgHRkqWVgDqf4OkX1soROOrRL9VZKc18Qp4qLfvHoQ6u305+lwCj9WzjOFHEUpSU
            7VWaO9DhTCM0Hbs93X3Zp1LQAzHg4BbRYfLw7ovJwsS/QF/+R5Xnl7Ou15zWS0E=
            =RhzR
            -----END PGP MESSAGE-----
          fp: 99F6DD21668C977FA0E35AB64C928FA9E7FF041B
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitlab-auth
  url: https://gitlab.com/abohmeed/myweatherapp
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: gitlab-auth
  type: oci
  url: oci://registry.gitlab.com/abohmeed/myweatherapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
