---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-auth
  namespace: apps
spec:
  encryptedData:
    password: AgBZucZMkTk9czBdVafq6n9uj4UkTivZ+6mRqpN9Z2XPMKex075GteKDHFF5jfpFxhD9NmB5lLP2rafsMU0gRY09TcRgd4vrAEAVIjlJ5fn0J9aHS8LXVkOZaM8bCibfr4w78RqGfPevXSGh0YQMl0JNzyT8OCv5in+XxPJwJ2yZyzmGdE6qpGUQIleGY2wlTq+Lpq4tmSmNOPo20LDhy706CS7LMriqLPO5N/ReM37HcXR5Z7xGaYHDmo1GICtR0drHZZg09oTt7MW19DHg5B8ZdroKTk8amf8HhDWVJ6tae+7I/NBxRU7zn8zYmKvfDSvNdpFV0rNNEf5saemmf1MoeNNU5s8IP5nOMpLvZoFhntejUUInvgOeJoKUn0UBQZkzH+uV5CLbr9y0Y4WzoqxhWybut5+h72guTCJ+AjgkZ46cvfFfEt5lu/hsBfRhwI4E5WBDJFdvr4gEG2BwQ1alQhNYjnWuU45okNSi5wgLORjArY8g8ZdWc9wJomHfOVDhNEyRVhbQO0mZBIjkZCaOzyZdP/oHNZlcQH+dsmAkN48ltwp3X6RkpyZuwqDrsY0ApiZnZvKs5gd9BLl/UFhxZkKd+wKxTwXXg4XEEo9H28xzp+CbEgr0XZynEuL39+g1B9Q0ZhoV721JfT4rJHS/XeGm9GfBgPRouPKtf2U+HD8ccVu0i8deRpq8PCVRuyh15PwdsasfEXUfZTNhwgb53sBCF8wHCrtMsqjEfKwh7HOLbJLO+91H
    username: AgBRh+cZHS8EmKEIZEjMLRUhq7/FXxf5rbv+VCvjgW839H4XXE7gGRWP/pMWAua6LF+zfqZPOvUfh/f34+q5/2v3IOrq851oTQhPksCJXsxZlnLqKVriA5B/a/ZJqxE+M+2azC9B1AvJpK89qimlNOugUe0uRgllXDGfm+Y8GHjtZucA780t69GOKACOQHhZ2Ct2EsqQd6uHxJAWbETIof4RdmUwGsQxN/zNuURUNN+brcm4Q0nC6pyIPyf11A90h2A3gj/fCaCG55mPoIwPLj7bTynVyQcIGXnrnO6rPB9ToTfQrJuvk332Ok78KQJh2knGSKYKssbR1CWMrhDOy/S5zYFmeTVP51JU3QcUxaUK1QNIqrBdd1id9A3kzo2IblH+s92DzLiiAvrwQnHo2Hmca/fm4EWxp226scvVJ2Wy5lc42MaFKQbio2WujV2bwcP+kJXBZvrlLhGMl93qBzSCKVPeDaDFL2iMleqIwnzwOtLEEKbuGnMG+vOM+AaL3+Rgt6CV90Gxby7cXIw4xE53clT036//xlGtxws/dDKSF1FG5qOZ7SCMiZ/FX4Y8aaCjy11E6XDlNx6BBo3yCrYYbBa8d1f1Uajnq4R7hGPrQnIplXCFPRRPChUPm9MiWj8AqAeyqjK6zS30gLbtWTHid9Zl/JTCOFKBAF9dv6TNTFe9VUlclL8EF/+RL742DYsBmQ1JkMKGV4fbUb3TXzhRzGk=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-auth
      namespace: apps
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: gitlab-auth
  type: oci
  url: oci://registry.gitlab.com/abohmeed/myweatherapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
