---
apiVersion: v1
kind: Secret
metadata:
    name: gitlab-auth
    namespace: apps
stringData:
    password: ENC[AES256_GCM,data:9JC7GFOmQuBvhpJsrKy/AtmzB2JqDewMO3Y=,iv:yBGBGxI/OsPbm+4gJ5NzoARTmFnklwhd2eXULkHTyxI=,tag:XsGMWqsCgnZaDTv5rIUCLQ==,type:str]
    username: ENC[AES256_GCM,data:Ql2/vJuxCPwOjD9Us5bFFUf5,iv:ckQ75JEJ5jd0tdalpSzs3nQlgkXk1TtvJMZG8YtppOA=,tag:SryBcxPxZP8pKsg2qaC+Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-29T10:51:31Z"
    mac: ENC[AES256_GCM,data:rStbqHIFaffACVDIFEmYptGmWv4vRzyeEEY5yu66iPWBDeEHa1vUHc138NHOiXdkNMQzOmtn35zti0orWZ9v5dMrf3jZa8/uwNl8H7cSf3DG+k3xv5dP82JwMDaf2UHfnk89FPEhUXE65FfXJBNr+nG8yeas5eoGqfksEVKSpUg=,iv:SPzcQSjCyhLm40FXQCpfjj5qL/t6Dwt8g5iXzch1OH0=,tag:faS9PNHx3S17B5GYPXOqtA==,type:str]
    pgp:
        - created_at: "2023-10-29T10:51:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+zeu3KaSuIcAQ//S4TLer3vsFJMikoYioxKstVwua+GdmjUWAddWoXLPHfT
            OgOG4XLfiWIod02htIvLI7Ol/MnoRYYN52E7v9BgWWKdCXwS291tPWelXQEBgPCS
            35L5mErYVjd0apB/Xd4LueQoavsIpOiHtTU12sx0AkIbt9115vwaDuTziMFmvj74
            X+0w/2TjhznGNveO5DTmpVYFv7hukha+VKhEPWe/VlB7z9LJyQHc26Za9ZLfU0Rp
            b3XPCOrmhiJxns4G9VaaT/v5g4tCDxAWJ0xa3qvqJhz/4wvBEJo7VvoKHUuuxYt7
            qBK4F3fm3/RNSPUTFL/7u/bSnvrKeYUtjnGfPDq8aAC5QoKN7ucfE5M4ApXCCx0V
            4NPWS0+f6QG0MabwCQWuvMUz++vd8hL1QsWPsBcJy/xf8wsz4nKqBinDdHq+5g0R
            DVN1x2u4vY4gIbjIt9Kisnki1HBk/nDuuvsPcA+pdzC3avmdM3yJjqdqPA/LJsZo
            A/y8uLJFgZ6mxPBQzceGEvruMHNpcTLwt2uXaBO8YPdzXkKUI6/BMG8Vw9IYc/HD
            648Pqnn9ZbNQXByBntWrUS4DlLVF3oc2fFLnRo2IGggZf2D/gi5KjbbRW6oHRnmS
            xXTcnC4YcL2TYTQYyaEApAPsUkJNTSgyG9CaMtVAUUE0Scub7+nvI65mUGq8MWbU
            aAEJAhAp2FkXoO8HaeFpUFX0ysWoJgfehc8GrnkBFgU1lwkEhfYV3VM1a+QlTGZ3
            gCOOfy9AcHkn/8GeTXWbBg5aAqdulh/vKMfAcnIq9Fz7jtOoMVuc7D1zRFZTT4gq
            Na5QLHiRGsqe
            =c99P
            -----END PGP MESSAGE-----
          fp: 6416894EFCF886766357879986C010747E095DDC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitlab-auth
  url: https://gitlab.com/abohmeed/myweatherapp
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gitlab
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: gitlab-auth
  type: oci
  url: oci://registry.gitlab.com/abohmeed/myweatherapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-hcvault
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: apps
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
